### ISSUE TITLE
Hourly email being generated by texttospeech module errors

### ISSUE THREAD

**Issue by lgaetz** [phwhite/texttospeech#2]
I am getting this email delivered hourly to user asterisk. FreePBX 2.9, Asterisk 1.8.  We see this problem with other modules when functions.inc.php generates any output.

```
From    root@pbx.local (Cron Daemon)
To  asterisk@pbx.local
Date    02/05/2012 09:21
Subject     Cron <asterisk@pbx> /var/lib/asterisk/bin/freepbx-cron-scheduler.php
Message contents    

which: no espeak in (/usr/bin:/bin)
which: no espeak in (/var/lib/asterisk/bin)
which: no google-tts in (/usr/bin:/bin)
which: no ms-tts in (/usr/bin:/bin)
sh: asterisk: command not found
which: no swift in (/usr/bin:/bin)
which: no swift in (/var/lib/asterisk/bin)
```

**Comment by phwhite** [comment]
You know I seen these in the freepbx/httpd log file, but I don't have the cron emails going anywhere on my systems at the moment, so I didn't realize it generated so much content!  I'll look into this today, and hopefully get it a fix out.  The 'which' lines I don't believe will be a problem, however the 'sh: asterisk: command not found' is a new one.  From the order of the message though, I know where to start looking.

Thanks for your bug report!  Will let you know when I've resolved it, should be sometime today.

**Comment by lgaetz** [comment]
The `sh: asterisk: command not found` may not be due to your module.  This is coming from my test system which at any given moment is throwing errors for lots of things.

**Comment by phwhite** [comment]
It looks like I found all of those output issues in the scripts.  I wasn't re-directed stderr of my exec() calls anywhere.  When you have the time, could you please download and extract this tarball:

https://github.com/downloads/phwhite/texttospeech/tts-cronfix-05020943.tgz

inside of the texttospeech module directory, and see if it solves your problem?  For example:

$ cd /var/www/html/admin/modules/texttospeech
$ wget https://github.com/downloads/phwhite/texttospeech/tts-cronfix-05020943.tgz
$ tar -zxvof tts-cronfix-05020943.tgz 

Thank you!

**Comment by lgaetz** [comment]
I installed your updated module linked above and am now getting this hourly email:

```
From    root@pbx.local (Cron Daemon)
To  asterisk@pbx.local
Date    02/05/2012 15:21
Subject     Cron <asterisk@pbx> /var/lib/asterisk/bin/freepbx-cron-scheduler.php
Message contents    

which: no asterisk in (/usr/bin:/bin)
```

Again, not 100% positive it is your module generating this but I think it is likely.

**Comment by phwhite** [comment]
Yah it's my module, it's the code that is using the asterisk binary to check whether app_swift is loaded and functioning.  I might have missed a spot on the stderr redirecting.  Looks like the other messages are taken care of though?  Sometime this evening or tomorrow morning I'll dive in and see where I missed that last one.

Again, thanks for your time and effort.
Paul

**Comment by phwhite** [comment]
Hi!  

These messages should no longer be an issue as of v2.0.0.3, which you can download at https://github.com/downloads/phwhite/texttospeech/texttospeech-2.0.0.3.tgz

Thanks
